### ISSUE TITLE
Request: LppFrame to json

### ISSUE THREAD

**Issue by baja2k9** [smlng/pycayennelpp#101]
Hi,
An example of  how to perform Lpp frame to json that would be great.

or better an internal converter, like:

frame = LppFrame().from_bytes(buffer)
my_json=frame.to_json()

**Comment by smlng** [comment]
I get your point, and I was thinking about extending the documentation for a while now - like readthedocs. However, I would not build JSON directly into the lib because it goes agains the idea of simplicity. Still this not a drawback, if frame exposes its data in `__dict__` or so, then it should be possible to convert it into json by a simple external call. 

I'll look into it soonish, thanks for the idea and pointer - much appreciated!!

**Comment by baja2k9** [comment]
Thank you for your great work!!

**Comment by smlng** [comment]
Hi again,

using the example from the README:
```python
from cayennelpp import LppFrame


# create empty frame
frame = LppFrame()
# add some sensor data
frame.add_temperature(0, -1.2)
frame.add_humidity(6, 34.5)
# get byte buffer in CayenneLPP format
buffer = bytes(frame)
```

would a JSON like this be okay for you:

```json
[
  {
    "channel": 0,
    "type": 103,
    "value": [
      -1.2
    ]
  },
  {
    "channel": 6,
    "type": 104,
    "value": [
      34.5
    ]
  }
]
```

?

**Comment by smlng** [comment]
could also encode type as string, i.e. temperature and humidity in the example above.

**Comment by smlng** [comment]
a bit background: do get a nice JSON we need a custom encoder function to pass into `json.dumps`. I tried using a `lambda` but that would not yield nice results or would be overly complicated for the user.

**Comment by smlng** [comment]
See #102 for a WIP solution

**Comment by baja2k9** [comment]
> Hi again,
> 
> using the example from the README:
> 
> ```python
> from cayennelpp import LppFrame
> 
> 
> # create empty frame
> frame = LppFrame()
> # add some sensor data
> frame.add_temperature(0, -1.2)
> frame.add_humidity(6, 34.5)
> # get byte buffer in CayenneLPP format
> buffer = bytes(frame)
> ```
> 
> would a JSON like this be okay for you:
> 
> ```json
> [
>   {
>     "channel": 0,
>     "type": 103,
>     "value": [
>       -1.2
>     ]
>   },
>   {
>     "channel": 6,
>     "type": 104,
>     "value": [
>       34.5
>     ]
>   }
> ]
> ```
> 
> ?

Hi,
I think the type would be better as a string like:Temperature,Voltage,Analog Input etc.  for quickly recognize the type of sensor.

Thanks for the quickly solution.
