### ISSUE TITLE
Decode example?

### ISSUE THREAD

**Issue by arrowcircle** [smlng/pycayennelpp#30]
Hi! I am new to python and struggling to decode data.
I try to use this code:

```
lpp = LppFrame()
decodedlpp = lpp.from_bytes(decoded64)
print("decodedlpp: ", decodedlpp)
```
and log
```
decoded64:  b'\x01g\x00\xe1\x02s)\xec\x03\x88\x08\x81\xe3\x05\xbd\x8b\x00\x00\xc8\x05hG'
decodedlpp:  <cayennelpp.lpp_frame.LppFrame object at 0x10255a518>
<cayennelpp.lpp_frame.LppFrame object at 0x10255a518>
```

What is the proper way of decoding payload with this library?

**Comment by smlng** [comment]
Hi @arrowcircle, you pointed out a missing feature ... right now there is no build in string version of a LppFrame. What you could do is something like
```python
lpp = LppFrame.from_bytes(decoded64)
for d in lpp.data:
    print(d)
```

There are several things to note: if the input is base64 encoded you can use `LppFrame.from_base64(data)`. Also `from_bytes` and `from_base64` are classmethods so no need to create a frame instance first.

But I will add `__string__`  for LppFrame to get some nice output without the workaround above.

**Comment by smlng** [comment]
Hey @arrowcircle please have a look at #31 which updates the [README](
https://github.com/smlng/pycayennelpp/pull/31/files#diff-04c6e90faac2675aa89e2176d2eec7d8) and adds a string representation to print LppFrames. Are these addition sufficient, at least to close this issue?

**Comment by smlng** [comment]
You're welcome, always good to get feedback from users 😄 

Closing.
