### ISSUE TITLE
Add more data formats

### ISSUE THREAD

**Issue by aparcar** [smlng/pycayennelpp#40]
Here are many more codes one could add. Does it make sense to extend the LLP standard?

**Comment by aparcar** [comment]
ping

**Comment by smlng** [comment]
Sorry for being quiet for some time. 

I was also thinking about adding more codes/types to support other sensors, however that only makes sense when reflected in the LPP standard *and* implemented by other libs/packages for LPP.

**Comment by dolfandringa** [comment]
@smlng The arduino CayenneLPP library does support additional formats: https://github.com/ElectronicCats/CayenneLPP
I would be happy to contribute a PR for (some of) those if you would accept the PR.

**Comment by smlng** [comment]
sure, I won't have time to work on this right now. So please make a PR with your additions.

**Comment by dolfandringa** [comment]
@smlng I made 3 PR's each for a separate type to keep it clean. But in my fork I have a separate develop branch that has all three merged in, so I can make a PR from that too that merges it all as one (and thus makes the merging easier).

**Comment by amotl** [comment]
Dear @dolfandringa and @smlng,

first things first: Thank you so much for maintaining and conceiving this library!

@thiasB is currently working on LoRa-support [1] for the [Terkin-Datalogger](https://github.com/hiveeyes/terkin-datalogger). So, I am humbly asking if we can get your contributions from #42 and #43 into mainline somehow?

With kind regards,
Andreas.

[1] https://github.com/thiasB/terkin-datalogger/commits/ttn_lora

**Comment by aparcar** [comment]
Looking at the implementation of the "official" [decoder](https://github.com/ElectronicCats/CayenneLPP/blob/master/decoders/decoder.js) I'd suggest to add all missing data formats.
