### ISSUE TITLE
Typo within LppFrame.add_humidity

### ISSUE THREAD

**Issue by amotl** [smlng/pycayennelpp#44]
When reviewing https://github.com/thiasB/terkin-datalogger/commit/11bd35be by @thiasB, I just spotted a typo within `lpp_frame.py`.

https://github.com/smlng/pycayennelpp/blob/c0e3bf6f44d402be4f43acaad1b3b217177868c2/cayennelpp/lpp_frame.py#L103

`add_humitidy` should actually be called `add_humidity` [1], right?

I suggest to rename the main function and to provide an alias for backward-compatibility like `add_humitidy = add_humidity` at the very bottom of the module.

**Comment by smlng** [comment]
@amotl nice find, I guess I should add a spell checker to the travis.yml to avoid such in the future. Do you really think we need backwards compatibility? I would rather make a new release and put in a note on this change.

So people can adapt their code or fix the package version to the old one.

Anyhow, you wanna make a PR?

**Comment by thiasB** [comment]
I go along with Andreas suggestion. You may remove the alias in the release following the next.
