### ISSUE TITLE
New release on PyPI

### ISSUE THREAD

**Issue by amotl** [smlng/pycayennelpp#49]
Dear Sebastian,

can I humbly ask you to push a 1.4.0 release to PyPI? Asking for a friend... ;]

Cheers,
Andreas,

**Comment by smlng** [comment]
I'm on it.  However, I planned to include some more stuff, but could do that in another update later on too.

**Comment by amotl** [comment]
Dear Sebastian,

thanks a bunch for putting out 1.4.0 [1,2]!

With kind regards,
Andreas.

[1] https://github.com/smlng/pycayennelpp/releases/tag/v1.4.0
[2] https://pypi.org/project/pycayennelpp/1.4.0/

cc @thiasB

**Comment by amotl** [comment]
Dear Sebastian,

I've just rebased the work of @dolfandringa (#42 and #43) and created respective pull requests (#50 and #51). Can I humbly ask you to review the changes and push out another release 1.5.0?

Thanks already and with kind regards,
Andreas.

**Comment by smlng** [comment]
yeah, but for 1.5.0 I really would like to include some more code improvements, specifically deduplication - which I already started recently.

**Comment by smlng** [comment]
release 1.5.0 is out

**Comment by amotl** [comment]
Dear Sebastian,

thanks a bunch for that. We appreciate all your work on this fine library. Stay safe and keep up the spirit!

With kind regards,
Andreas.

cc @thiasB
