### ISSUE TITLE
Unix Time support for MicroPython

### ISSUE THREAD

**Issue by amotl** [smlng/pycayennelpp#53]
Hi there,

within #51, we are discussing _CayenneLPP Unix Time_ type compatibility with MicroPython.

@smlng said:
> This adds dependencies to `datetime` and `tz`. I am not sure about appropriate support in MicroPython - though the status of MicroPython is a bit unclear to me, too.

@amotl said:
> Indeed, we are using the library on MicroPython through our [Terkin Datalogger](https://github.com/hiveeyes/terkin-datalogger) and would like it to stay compatible with MicroPython.

I will check whether the current implementation would work using the MicroPython datetime module [1] and document the process within this issue.

With kind regards,
Andreas.

[1] https://github.com/micropython/micropython-lib/blob/master/datetime/datetime.py

**Comment by amotl** [comment]
I will check whether the current implementation would work using the MicroPython `datetime` module.

```
Pycom MicroPython 1.20.2.rc6-0.10.2-vanilla-squirrel-nosmartconfig [v1.20.1.r2-122-gd82a6f43e-dirty] on 2020-03-06; FiPy with ESP32
Type "help()" for more information.
>>>
>>> from cayennelpp import LppFrame
>>> frame = LppFrame()
>>> frame.add_unix_time(0, 1590010843)

>>> print(frame)
LppFrame(data = [
  LppData(channel = 0, type = Unix Time, value = (1590010843,))
])

>>> frame.bytes()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cayennelpp/lpp_frame.py", line 61, in bytes
  File "cayennelpp/lpp_data.py", line 61, in bytes
  File "cayennelpp/lpp_type.py", line 221, in lpp_unix_time_to_bytes
  File "datetime.py", line 1919, in <module>
  File "datetime.py", line 1836, in _create
AttributeError: type object 'tzinfo' has no attribute '__new__'
```

It does not work out of the box yet. Bummer!

**Comment by amotl** [comment]
After following https://github.com/micropython/micropython-lib/issues/319 and applying https://github.com/micropython/micropython-lib/issues/319 to the [MicroPython datetime module](https://github.com/micropython/micropython-lib/blob/master/datetime/datetime.py), at least importing `timezone` works. However, now I am getting:

```
>>> from cayennelpp import LppFrame
>>> frame = LppFrame()
>>> frame.add_unix_time(0, 1590010843)
>>> frame.bytes()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cayennelpp/lpp_frame.py", line 61, in bytes
  File "cayennelpp/lpp_data.py", line 61, in bytes
  File "cayennelpp/lpp_type.py", line 231, in lpp_unix_time_to_bytes
  File "datetime.py", line 1370, in fromtimestamp
TypeError: can't convert float to int
```

**Comment by amotl** [comment]
After fixing this like
```
# MicroPython does not accept fractions of seconds to "time.gmtime()".
t = int(t)
```

this is next:
```
>>> from cayennelpp import LppFrame
>>> frame = LppFrame()
>>> frame.add_unix_time(0, 1590010843)
>>> frame.bytes()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cayennelpp/lpp_frame.py", line 61, in bytes
  File "cayennelpp/lpp_data.py", line 61, in bytes
  File "cayennelpp/lpp_type.py", line 231, in lpp_unix_time_to_bytes
  File "datetime.py", line 1374, in fromtimestamp
ValueError: need more than 8 values to unpack
```

**Comment by amotl** [comment]
Encoding works now:
```
>>> from cayennelpp import LppFrame
>>> frame = LppFrame()
>>> frame.add_unix_time(0, 1590010843)
>>> frame.bytes()
bytearray(b'\x00\x85^\xc5\xa3\xdb')
```

**Comment by amotl** [comment]
So, we conclude it should be safe to merge #51, when taking into account that the MicroPython `datetime` module needs some updates, which have been implemented within [`datetime.py`](https://github.com/daq-tools/pycopy-lib/blob/improve-datetime/datetime/datetime.py) through https://github.com/daq-tools/pycopy-lib/commit/5c8e8342.

**Comment by amotl** [comment]
Sebastian suggested to

> use the same code as for the generic uint but with the correct type for unix timestamp and use integer as input and output. The user would then do something like
```
# Encode
from datetime import datetime
frame = LppFrame()
frame.add_unix_time(datetime.now().timestamp())

# Decode
dt = datetime.fromtimestamp(frame.data[0].value)
```

**Comment by smlng** [comment]
Let's keep this open until we have this feature in - independent of the implemented solution.

**Comment by smlng** [comment]
basic implementation done in #56
